### ISSUE TITLE
stoned on top

### ISSUE THREAD

**Issue by Kyxnite** [Joseloll/Ip-Puller#1]
Yo bro its stoned.eagle

lets talk at discord.gg/botnet i missed u my favorite beaner

**Comment by Joseloll** [comment]
What’s sup man been while

**Comment by Kyxnite** [comment]
Yoo add my new account bro stoned#9020

**Comment by Kyxnite** [comment]
discord.gg/botnet

**Comment by EvilBytecode** [comment]
🤣  .gg/botnet filled w skidz?
